name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ha01821113/portfolio-website
          stage: main
          yaml: >
            name: hjh-portfolio

            app: java@17

            options:
              ports: "8081"
              env:
                - name: SPRING_DATASOURCE_URL
                  value: ${{ secrets.SPRING_DATASOURCE_URL }}
                - name: SPRING_MAIL_HOST
                  value: ${{ secrets.SPRING_MAIL_HOST }}
                - name: SPRING_MAIL_PORT
                  value: ${{ secrets.SPRING_MAIL_PORT }}
                - name: SPRING_MAIL_USERNAME
                  value: ${{ secrets.SPRING_MAIL_USERNAME }}
                - name: SPRING_MAIL_PASSWORD
                  value: ${{ secrets.SPRING_MAIL_PASSWORD }}
                - name: SPRING_DATASOURCE_USERNAME
                  value: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
                - name: SPRING_DATASOURCE_PASSWORD
                  value: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
              buildenv: []
              includes: src
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
